//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::friend_requests::Entity as FriendRequests;
pub use super::friends::Entity as Friends;
pub use super::promotions::Entity as Promotions;
pub use super::users::Entity as Users;
